[package]
name = "fsr-rust"
version = "0.1.0"
authors = ["Romain Ruetschi <romain.ruetschi@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
slug = "0.1.4"
frontmatter = "0.3.0"
yaml-rust = "0.3.5"
comrak = "0.6.2"
serde_derive = "1.0.101"
serde = "1.0.101"
image = "0.22.3"
once_cell = "1.2.0"
csv = "1.1.1"
itertools = "0.8.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["serve", "tera_templates"]

