[package]
name = "fsr-rust"
version = "0.1.0"
authors = ["Romain Ruetschi <romain.ruetschi@gmail.com>"]
edition = "2018"

[dependencies]
slug = "0.1.4"
frontmatter = "0.3.0"
yaml-rust = "0.3.5"
comrak = "0.7.0"
serde_derive = "1.0.104"
serde = "1.0.104"
image = "0.22.4"
once_cell = "1.3.1"
csv = "1.1.3"
itertools = "0.8.2"
winapi = "0.3.7"
notify = "5.0.0-pre.2"
hotwatch = "0.4.3"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket/"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket/"
default-features = false
features = ["serve", "tera_templates", "compression"]

