[package]
name = "fsr-rust"
version = "0.1.0"
authors = ["Romain Ruetschi <romain.ruetschi@gmail.com>"]
edition = "2018"

[dependencies]
async-std    = { version = "1.8.0", features = ["attributes", "unstable"] }
comrak       = "0.9.0"
csv          = "1.1.4"
frontmatter  = "0.4.0"
hotwatch     = "0.4.5"
itertools    = "0.9.0"
notify       = "5.0.0-pre.4"
once_cell    = "1.5.2"
serde        = "1.0.118"
serde_derive = "1.0.118"
slug         = "0.1.4"
yaml-rust    = "0.4.4"
tide         = "0.15.0"
tide-tera = "0.2.3"
tide-compress = "0.8.1"
tera = "1.5.0"
arc-swap = "1.1.0"
