[package]
name = "fsr-rust"
version = "0.1.0"
authors = ["Romain Ruetschi <romain.ruetschi@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
im = "13.0.0"
slug = "0.1.4"
frontmatter = "0.3.0"
lazy_static = "1.4.0"
yaml-rust = "0.3.5"
comrak = "0.6.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["serve", "tera_templates"]

