[package]
name = "fsr-rust"
version = "0.1.0"
authors = ["Romain Ruetschi <romain.ruetschi@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0-rc.1"
typed-html = "0.1.1"
typed-html-macros = "0.1.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.1"
default-features = false
features = ["serve"]

